<?php

namespace ContainerFeNG9QT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0Ep3N7JService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0Ep3N7J' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0Ep3N7J'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CommuneController::delete' => ['privates', '.service_locator.zfefn9l', 'get_ServiceLocator_Zfefn9lService', true],
            'App\\Controller\\CommuneController::edit' => ['privates', '.service_locator.zfefn9l', 'get_ServiceLocator_Zfefn9lService', true],
            'App\\Controller\\CommuneController::index' => ['privates', '.service_locator.f_pHdD.', 'get_ServiceLocator_FPHdD_Service', true],
            'App\\Controller\\CommuneController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\CommuneController::show' => ['privates', '.service_locator.yNEvuU.', 'get_ServiceLocator_YNEvuU_Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\CommuneController:delete' => ['privates', '.service_locator.zfefn9l', 'get_ServiceLocator_Zfefn9lService', true],
            'App\\Controller\\CommuneController:edit' => ['privates', '.service_locator.zfefn9l', 'get_ServiceLocator_Zfefn9lService', true],
            'App\\Controller\\CommuneController:index' => ['privates', '.service_locator.f_pHdD.', 'get_ServiceLocator_FPHdD_Service', true],
            'App\\Controller\\CommuneController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\CommuneController:show' => ['privates', '.service_locator.yNEvuU.', 'get_ServiceLocator_YNEvuU_Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\CommuneController::delete' => '?',
            'App\\Controller\\CommuneController::edit' => '?',
            'App\\Controller\\CommuneController::index' => '?',
            'App\\Controller\\CommuneController::new' => '?',
            'App\\Controller\\CommuneController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CommuneController:delete' => '?',
            'App\\Controller\\CommuneController:edit' => '?',
            'App\\Controller\\CommuneController:index' => '?',
            'App\\Controller\\CommuneController:new' => '?',
            'App\\Controller\\CommuneController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
