<?php

namespace ContainerFeNG9QT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FPHdD_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.f_pHdD.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.f_pHdD.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'communeRepository' => ['privates', 'App\\Repository\\CommuneRepository', 'getCommuneRepositoryService', true],
        ], [
            'communeRepository' => 'App\\Repository\\CommuneRepository',
        ]);
    }
}
