<?php

namespace ContainerFeNG9QT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YNEvuU_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yNEvuU.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yNEvuU.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commune' => ['privates', '.errored..service_locator.yNEvuU..App\\Entity\\Commune', NULL, 'Cannot autowire service ".service_locator.yNEvuU.": it references class "App\\Entity\\Commune" but no such service exists.'],
        ], [
            'commune' => 'App\\Entity\\Commune',
        ]);
    }
}
