<?php

namespace ContainerFeNG9QT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Zfefn9lService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zfefn9l' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zfefn9l'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commune' => ['privates', '.errored..service_locator.zfefn9l.App\\Entity\\Commune', NULL, 'Cannot autowire service ".service_locator.zfefn9l": it references class "App\\Entity\\Commune" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'commune' => 'App\\Entity\\Commune',
            'entityManager' => '?',
        ]);
    }
}
