<?php

namespace ContainerFeNG9QT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommuneService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.yNEvuU..App\Entity\Commune' shared service.
     *
     * @return \App\Entity\Commune
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.yNEvuU.": it references class "App\\Entity\\Commune" but no such service exists.');
    }
}
