<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFeNG9QT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFeNG9QT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFeNG9QT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFeNG9QT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFeNG9QT\App_KernelDevDebugContainer([
    'container.build_hash' => 'FeNG9QT',
    'container.build_id' => '1d0017b4',
    'container.build_time' => 1671396091,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFeNG9QT');
