<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_api_localidad' => [[], ['_controller' => 'App\\Controller\\ApiController::index'], [], [['text', '/api/localidad']], [], []],
    'app_api_localidad_all' => [[], ['_controller' => 'App\\Controller\\ApiController::all'], [], [['text', '/api/localidad/all']], [], []],
    'app_api_localidad_ids' => [['ids'], ['_controller' => 'App\\Controller\\ApiController::add'], [], [['text', '/'], ['variable', '/', '[^/]++', 'ids', true], ['text', '/api/api/localidad']], [], []],
    'app_commune_index' => [[], ['_controller' => 'App\\Controller\\CommuneController::index'], [], [['text', '/commune/']], [], []],
    'app_commune_new' => [[], ['_controller' => 'App\\Controller\\CommuneController::new'], [], [['text', '/commune/new']], [], []],
    'app_commune_show' => [['id'], ['_controller' => 'App\\Controller\\CommuneController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/commune']], [], []],
    'app_commune_edit' => [['id'], ['_controller' => 'App\\Controller\\CommuneController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/commune']], [], []],
    'app_commune_delete' => [['id'], ['_controller' => 'App\\Controller\\CommuneController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/commune']], [], []],
    'app_main' => [[], ['_controller' => 'App\\Controller\\MainController::index'], [], [['text', '/main']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
