<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'js/app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_symfony_stimulus-bridge_dist_index_js-node_modules_symfony_ux-vue_dist_r-4ec35f.js',
                '/build/js/app.js',
            ],
            'css' => [
                '/build/vendors-node_modules_symfony_stimulus-bridge_dist_index_js-node_modules_symfony_ux-vue_dist_r-4ec35f.css',
                '/build/js/app.css',
            ],
        ],
    ],
],

]];
